name: setup_node
description: Checkout code, setup Node, and install Pnpm
inputs:
  node-version:
    required: true
    description: The version of Node to use.
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
