version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-*
  - temp
  - coverage
  - '*.snap'
dictionaryDefinitions: []
dictionaries: ['typescript']
words:
  - autobuild
  - buildscript
  - codecov
  - codeql
  - coverallsapp
  - globby
  - lcov
  - mdast
  - pnpm
  - unist
  - vfile
ignoreWords: []
import: []
