version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-*
  - temp
  - coverage
  - '*.snap'
  - fixtures/remote-responses
  - CHANGELOG.md
dictionaryDefinitions: []
dictionaries:
  - typescript
words:
  - autobuild
  - autolinks
  - basenames
  - buildscript
  - codecov
  - codeql
  - coverallsapp
  - footgun
  - frontmatter
  - globby
  - HKLM
  - kubeconfig
  - lcov
  - mdast
  - metacharacters
  - pnpm
  - restringify
  - setext
  - stringifying
  - strikethrough
  - syscall
  - unist
  - uppercasing
  - vfile
  - worktree
  - worktrees
ignoreWords: []
import: []
