version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autobuild
  - buildscript
  - codecov
  - codeql
  - coverallsapp
  - globby
  - mdast
  - pnpm
  - unist
  - vfile
ignoreWords: []
import: []
