name: install_build_test
description: Install Build and Test
inputs:
  node-version:
    required: true
    description: The version of Node to use.
runs:
  using: 'composite'
  steps:
    - name: Setup
      # Directory name only
      uses: ./.github/actions/setup
      with:
        node-version: ${{ inputs.node-version }}
    - shell: bash
      run: |
        pnpm i
        pnpm run build
        pnpm test
