# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: lint-${{ inputs.base ||  github.ref || 'main' }}
      REF_BRANCH: ${{ inputs.base || github.ref || 'main' }}
      PR_TYPE: ci
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_BRANCH }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: |
          pnpm build
          pnpm lint:fix

      - name: Gen Body
        run: |
          echo 'git_body<<DIFF' >> $GITHUB_ENV
          git --no-pager diff --compact-summary >> $GITHUB_ENV
          echo 'DIFF' >> $GITHUB_ENV

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: '${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: '${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies (${{ env.REF_BRANCH }})'
          body: ${{ env.git_body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
