name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  # cspell:ignore noreply

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - run: |
          pnpm i
          pnpm build

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM}}
